version: '3'

services:
  fah-client:
    #image: yurinnick/folding-at-home
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fah
    volumes:
      - "./config.xml:/opt/fah/config.xml"
      - "./work/:/opt/fah/work/"
    environment:
#      - USER=<Username>
#      - TEAM=<TeamID>
#      - PASSKEY=<PassKey>
      - ENABLE_SMP=true
      - ENABLE_GPU=false
    ports:
      - 7396:7396
      - 36330:36330
    restart: unless-stopped
    network_mode: "bridge"
